M  bin/data_select;M  bin/mpvl;A  cava/.gitignore

diff --git a/bin/mpvl b/bin/mpvl
--- a/bin/mpvl
+++ b/bin/mpvl
@@ -1,26 +1,10 @@
-#!/usr/bin/env fish
-set file '/home/user/projects/other/files/mpvl_list'
-if not test -f $file
-    echo "file $file not found"
+#!/bin/sh
+file='/home/user/projects/other/files/mpvl_list'
+test ! -f $file&&echo "file $file not found"&&exit 1
+act=$(grep "^$1\s" $file | cut -f2)
+if test -z "$act";then
+    echo "possible actions: $(cat $file | cut -f1 | tr '\n' ',')"
+    test -n "$1"&&echo "unknown action: $1"
     exit 1
-end
-for line in (cat $file)
-    set key (echo $line|cut -f1)
-    set acts $acts $key
-    if test $key = "$argv[1]"
-        set act (echo $line|cut -f2)
-        set extra (echo $line|cut -f3)
-    end
-end
-if test -z "$act"
-    echo "possible actions: $(string join ', ' $acts)"
-    if test -n "$argv[1]"
-        echo "unknown action: $argv[1]"
-    end
-    exit 1
-end
-if test $extra = LOOPFILE
-    mpv (eval $act) --no-video --shuffle --loop
-else
-    mpv (eval $act) --no-video --shuffle
-end
+fi
+mpv "$(eval "$act")" --no-video --shuffle
